cache:
  CACHE_TYPE: simple
app:
  SALT: bar
  ENV: dev
  SECRET: ^753*&FdFS#4D
  HOST: 127.0.0.1
  PORT: 5000
jwt:
  SECRET: foo
  EXPIRE_HOURS: 24
db:
  MYSQL: mysql+pymysql://thss:H0lc2FaAm30zV9r2@bj-cdb-jh34xs8y.sql.tencentcdb.com:62554/simplebbs?charset=utf8mb4